# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI10.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 1011)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 1024))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setItalic(True)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/fau.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.title_grid = QtGui.QFrame(self.centralwidget)
        self.title_grid.setMinimumSize(QtCore.QSize(0, 0))
        self.title_grid.setObjectName(_fromUtf8("title_grid"))
        self.gridLayout_6 = QtGui.QGridLayout(self.title_grid)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_logged_in = QtGui.QLabel(self.title_grid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logged_in.sizePolicy().hasHeightForWidth())
        self.label_logged_in.setSizePolicy(sizePolicy)
        self.label_logged_in.setMinimumSize(QtCore.QSize(0, 0))
        self.label_logged_in.setMaximumSize(QtCore.QSize(1280, 350))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_logged_in.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_logged_in.setFont(font)
        self.label_logged_in.setTextFormat(QtCore.Qt.PlainText)
        self.label_logged_in.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logged_in.setWordWrap(True)
        self.label_logged_in.setObjectName(_fromUtf8("label_logged_in"))
        self.gridLayout_6.addWidget(self.label_logged_in, 2, 1, 1, 1)
        self.label_logged_in_name = QtGui.QLabel(self.title_grid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logged_in_name.sizePolicy().hasHeightForWidth())
        self.label_logged_in_name.setSizePolicy(sizePolicy)
        self.label_logged_in_name.setMinimumSize(QtCore.QSize(0, 0))
        self.label_logged_in_name.setMaximumSize(QtCore.QSize(1280, 350))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_logged_in_name.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_logged_in_name.setFont(font)
        self.label_logged_in_name.setText(_fromUtf8(""))
        self.label_logged_in_name.setTextFormat(QtCore.Qt.PlainText)
        self.label_logged_in_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logged_in_name.setWordWrap(True)
        self.label_logged_in_name.setObjectName(_fromUtf8("label_logged_in_name"))
        self.gridLayout_6.addWidget(self.label_logged_in_name, 2, 2, 1, 1)
        self.logo = QtGui.QLabel(self.title_grid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(150, 50))
        self.logo.setMaximumSize(QtCore.QSize(250, 75))
        self.logo.setText(_fromUtf8(""))
        self.logo.setPixmap(QtGui.QPixmap(_fromUtf8("faurecia.png")))
        self.logo.setScaledContents(True)
        self.logo.setObjectName(_fromUtf8("logo"))
        self.gridLayout_6.addWidget(self.logo, 1, 0, 1, 1)
        self.label_titulo = QtGui.QLabel(self.title_grid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo.sizePolicy().hasHeightForWidth())
        self.label_titulo.setSizePolicy(sizePolicy)
        self.label_titulo.setMinimumSize(QtCore.QSize(0, 0))
        self.label_titulo.setMaximumSize(QtCore.QSize(1280, 350))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_titulo.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setTextFormat(QtCore.Qt.PlainText)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setWordWrap(True)
        self.label_titulo.setObjectName(_fromUtf8("label_titulo"))
        self.gridLayout_6.addWidget(self.label_titulo, 0, 1, 2, 2)
        self.gridLayout.addWidget(self.title_grid, 0, 0, 1, 1)
        self.tempo = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempo.sizePolicy().hasHeightForWidth())
        self.tempo.setSizePolicy(sizePolicy)
        self.tempo.setMaximumSize(QtCore.QSize(1255, 400))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tempo.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(120)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tempo.setFont(font)
        self.tempo.setAutoFillBackground(True)
        self.tempo.setStyleSheet(_fromUtf8("tempo.background-color : red "))
        self.tempo.setTextFormat(QtCore.Qt.AutoText)
        self.tempo.setAlignment(QtCore.Qt.AlignCenter)
        self.tempo.setObjectName(_fromUtf8("tempo"))
        self.gridLayout.addWidget(self.tempo, 1, 0, 1, 1)
        self.data_grid = QtGui.QFrame(self.centralwidget)
        self.data_grid.setObjectName(_fromUtf8("data_grid"))
        self.gridLayout_2 = QtGui.QGridLayout(self.data_grid)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_7 = QtGui.QSplitter(self.data_grid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_7.sizePolicy().hasHeightForWidth())
        self.splitter_7.setSizePolicy(sizePolicy)
        self.splitter_7.setMaximumSize(QtCore.QSize(811, 555611))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.splitter_7.setPalette(palette)
        self.splitter_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_7.setLineWidth(0)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setHandleWidth(6)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.splitter_8 = QtGui.QSplitter(self.splitter_7)
        self.splitter_8.setMaximumSize(QtCore.QSize(811, 50))
        self.splitter_8.setFrameShape(QtGui.QFrame.Box)
        self.splitter_8.setLineWidth(3)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.label_ultimos = QtGui.QLabel(self.splitter_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ultimos.sizePolicy().hasHeightForWidth())
        self.label_ultimos.setSizePolicy(sizePolicy)
        self.label_ultimos.setMinimumSize(QtCore.QSize(0, 50))
        self.label_ultimos.setMaximumSize(QtCore.QSize(300, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_ultimos.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_ultimos.setFont(font)
        self.label_ultimos.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_ultimos.setLineWidth(1)
        self.label_ultimos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ultimos.setWordWrap(True)
        self.label_ultimos.setObjectName(_fromUtf8("label_ultimos"))
        self.data_hora_ultimos = QtGui.QLabel(self.splitter_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_hora_ultimos.sizePolicy().hasHeightForWidth())
        self.data_hora_ultimos.setSizePolicy(sizePolicy)
        self.data_hora_ultimos.setMinimumSize(QtCore.QSize(0, 50))
        self.data_hora_ultimos.setMaximumSize(QtCore.QSize(197, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_hora_ultimos.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.data_hora_ultimos.setFont(font)
        self.data_hora_ultimos.setFrameShape(QtGui.QFrame.NoFrame)
        self.data_hora_ultimos.setAlignment(QtCore.Qt.AlignCenter)
        self.data_hora_ultimos.setWordWrap(True)
        self.data_hora_ultimos.setObjectName(_fromUtf8("data_hora_ultimos"))
        self.label_user_latest = QtGui.QLabel(self.splitter_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_latest.sizePolicy().hasHeightForWidth())
        self.label_user_latest.setSizePolicy(sizePolicy)
        self.label_user_latest.setMinimumSize(QtCore.QSize(0, 50))
        self.label_user_latest.setMaximumSize(QtCore.QSize(300, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_user_latest.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_user_latest.setFont(font)
        self.label_user_latest.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_user_latest.setLineWidth(1)
        self.label_user_latest.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_latest.setWordWrap(True)
        self.label_user_latest.setObjectName(_fromUtf8("label_user_latest"))
        self.tabela_ultimos = QtGui.QTableWidget(self.splitter_7)
        self.tabela_ultimos.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabela_ultimos.sizePolicy().hasHeightForWidth())
        self.tabela_ultimos.setSizePolicy(sizePolicy)
        self.tabela_ultimos.setMinimumSize(QtCore.QSize(350, 320))
        self.tabela_ultimos.setMaximumSize(QtCore.QSize(55555, 555555))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tabela_ultimos.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tabela_ultimos.setFont(font)
        self.tabela_ultimos.setFrameShape(QtGui.QFrame.Box)
        self.tabela_ultimos.setFrameShadow(QtGui.QFrame.Plain)
        self.tabela_ultimos.setLineWidth(2)
        self.tabela_ultimos.setMidLineWidth(5)
        self.tabela_ultimos.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabela_ultimos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabela_ultimos.setAutoScroll(False)
        self.tabela_ultimos.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabela_ultimos.setTabKeyNavigation(False)
        self.tabela_ultimos.setProperty("showDropIndicator", False)
        self.tabela_ultimos.setDragDropOverwriteMode(False)
        self.tabela_ultimos.setAlternatingRowColors(True)
        self.tabela_ultimos.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tabela_ultimos.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tabela_ultimos.setWordWrap(True)
        self.tabela_ultimos.setCornerButtonEnabled(False)
        self.tabela_ultimos.setRowCount(10)
        self.tabela_ultimos.setColumnCount(3)
        self.tabela_ultimos.setObjectName(_fromUtf8("tabela_ultimos"))
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_ultimos.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tabela_ultimos.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabela_ultimos.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_ultimos.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_ultimos.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_ultimos.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tabela_ultimos.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_ultimos.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_ultimos.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_ultimos.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_ultimos.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_ultimos.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_ultimos.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_ultimos.setItem(9, 1, item)
        self.tabela_ultimos.horizontalHeader().setVisible(False)
        self.tabela_ultimos.horizontalHeader().setCascadingSectionResizes(False)
        self.tabela_ultimos.horizontalHeader().setDefaultSectionSize(153)
        self.tabela_ultimos.horizontalHeader().setHighlightSections(True)
        self.tabela_ultimos.horizontalHeader().setMinimumSectionSize(100)
        self.tabela_ultimos.horizontalHeader().setSortIndicatorShown(False)
        self.tabela_ultimos.horizontalHeader().setStretchLastSection(True)
        self.tabela_ultimos.verticalHeader().setVisible(True)
        self.tabela_ultimos.verticalHeader().setCascadingSectionResizes(False)
        self.tabela_ultimos.verticalHeader().setDefaultSectionSize(40)
        self.tabela_ultimos.verticalHeader().setHighlightSections(True)
        self.tabela_ultimos.verticalHeader().setMinimumSectionSize(40)
        self.tabela_ultimos.verticalHeader().setSortIndicatorShown(False)
        self.tabela_ultimos.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.splitter_7, 0, 0, 1, 1)
        self.splitter_6 = QtGui.QSplitter(self.data_grid)
        self.splitter_6.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(False)
        self.splitter_6.setFont(font)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setOpaqueResize(True)
        self.splitter_6.setHandleWidth(6)
        self.splitter_6.setChildrenCollapsible(True)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.splitter_5 = QtGui.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.label_objectivo = QtGui.QLabel(self.splitter_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_objectivo.sizePolicy().hasHeightForWidth())
        self.label_objectivo.setSizePolicy(sizePolicy)
        self.label_objectivo.setMinimumSize(QtCore.QSize(0, 50))
        self.label_objectivo.setMaximumSize(QtCore.QSize(1677215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_objectivo.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_objectivo.setFont(font)
        self.label_objectivo.setFrameShape(QtGui.QFrame.Box)
        self.label_objectivo.setFrameShadow(QtGui.QFrame.Plain)
        self.label_objectivo.setLineWidth(3)
        self.label_objectivo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_objectivo.setWordWrap(True)
        self.label_objectivo.setObjectName(_fromUtf8("label_objectivo"))
        self.tempo_objectivo = QtGui.QLabel(self.splitter_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempo_objectivo.sizePolicy().hasHeightForWidth())
        self.tempo_objectivo.setSizePolicy(sizePolicy)
        self.tempo_objectivo.setMinimumSize(QtCore.QSize(0, 50))
        self.tempo_objectivo.setMaximumSize(QtCore.QSize(1677215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tempo_objectivo.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.tempo_objectivo.setFont(font)
        self.tempo_objectivo.setFrameShape(QtGui.QFrame.NoFrame)
        self.tempo_objectivo.setFrameShadow(QtGui.QFrame.Plain)
        self.tempo_objectivo.setLineWidth(3)
        self.tempo_objectivo.setAlignment(QtCore.Qt.AlignCenter)
        self.tempo_objectivo.setObjectName(_fromUtf8("tempo_objectivo"))
        self.bola = QtGui.QLabel(self.splitter_6)
        self.bola.setText(_fromUtf8(""))
        self.bola.setPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/1.png")))
        self.bola.setScaledContents(False)
        self.bola.setAlignment(QtCore.Qt.AlignCenter)
        self.bola.setObjectName(_fromUtf8("bola"))
        self.gridLayout_2.addWidget(self.splitter_6, 0, 2, 1, 1)
        self.splitter_9 = QtGui.QSplitter(self.data_grid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_9.sizePolicy().hasHeightForWidth())
        self.splitter_9.setSizePolicy(sizePolicy)
        self.splitter_9.setMaximumSize(QtCore.QSize(811, 5611))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.splitter_9.setPalette(palette)
        self.splitter_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter_9.setLineWidth(0)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setHandleWidth(6)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.splitter_10 = QtGui.QSplitter(self.splitter_9)
        self.splitter_10.setMaximumSize(QtCore.QSize(811, 50))
        self.splitter_10.setFrameShape(QtGui.QFrame.Box)
        self.splitter_10.setLineWidth(3)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.label_melhores = QtGui.QLabel(self.splitter_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_melhores.sizePolicy().hasHeightForWidth())
        self.label_melhores.setSizePolicy(sizePolicy)
        self.label_melhores.setMinimumSize(QtCore.QSize(0, 50))
        self.label_melhores.setMaximumSize(QtCore.QSize(300, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_melhores.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_melhores.setFont(font)
        self.label_melhores.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_melhores.setLineWidth(1)
        self.label_melhores.setAlignment(QtCore.Qt.AlignCenter)
        self.label_melhores.setWordWrap(True)
        self.label_melhores.setObjectName(_fromUtf8("label_melhores"))
        self.data_hora_melhores = QtGui.QLabel(self.splitter_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_hora_melhores.sizePolicy().hasHeightForWidth())
        self.data_hora_melhores.setSizePolicy(sizePolicy)
        self.data_hora_melhores.setMinimumSize(QtCore.QSize(0, 50))
        self.data_hora_melhores.setMaximumSize(QtCore.QSize(197, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_hora_melhores.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.data_hora_melhores.setFont(font)
        self.data_hora_melhores.setFrameShape(QtGui.QFrame.NoFrame)
        self.data_hora_melhores.setAlignment(QtCore.Qt.AlignCenter)
        self.data_hora_melhores.setWordWrap(True)
        self.data_hora_melhores.setObjectName(_fromUtf8("data_hora_melhores"))
        self.label_user_best = QtGui.QLabel(self.splitter_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_best.sizePolicy().hasHeightForWidth())
        self.label_user_best.setSizePolicy(sizePolicy)
        self.label_user_best.setMinimumSize(QtCore.QSize(0, 50))
        self.label_user_best.setMaximumSize(QtCore.QSize(300, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_user_best.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_user_best.setFont(font)
        self.label_user_best.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_user_best.setLineWidth(1)
        self.label_user_best.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_best.setWordWrap(True)
        self.label_user_best.setObjectName(_fromUtf8("label_user_best"))
        self.tabela_melhores = QtGui.QTableWidget(self.splitter_9)
        self.tabela_melhores.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabela_melhores.sizePolicy().hasHeightForWidth())
        self.tabela_melhores.setSizePolicy(sizePolicy)
        self.tabela_melhores.setMinimumSize(QtCore.QSize(350, 320))
        self.tabela_melhores.setMaximumSize(QtCore.QSize(55555, 5555))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tabela_melhores.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tabela_melhores.setFont(font)
        self.tabela_melhores.setFrameShape(QtGui.QFrame.Box)
        self.tabela_melhores.setFrameShadow(QtGui.QFrame.Plain)
        self.tabela_melhores.setLineWidth(2)
        self.tabela_melhores.setMidLineWidth(5)
        self.tabela_melhores.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabela_melhores.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tabela_melhores.setAutoScroll(False)
        self.tabela_melhores.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabela_melhores.setTabKeyNavigation(False)
        self.tabela_melhores.setProperty("showDropIndicator", False)
        self.tabela_melhores.setDragDropOverwriteMode(False)
        self.tabela_melhores.setAlternatingRowColors(True)
        self.tabela_melhores.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tabela_melhores.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tabela_melhores.setWordWrap(True)
        self.tabela_melhores.setCornerButtonEnabled(False)
        self.tabela_melhores.setRowCount(10)
        self.tabela_melhores.setColumnCount(3)
        self.tabela_melhores.setObjectName(_fromUtf8("tabela_melhores"))
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(0, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(20, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tabela_melhores.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tabela_melhores.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabela_melhores.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_melhores.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_melhores.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_melhores.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tabela_melhores.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_melhores.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_melhores.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_melhores.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_melhores.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_melhores.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tabela_melhores.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tabela_melhores.setItem(9, 1, item)
        self.tabela_melhores.horizontalHeader().setVisible(False)
        self.tabela_melhores.horizontalHeader().setCascadingSectionResizes(False)
        self.tabela_melhores.horizontalHeader().setDefaultSectionSize(153)
        self.tabela_melhores.horizontalHeader().setHighlightSections(True)
        self.tabela_melhores.horizontalHeader().setMinimumSectionSize(100)
        self.tabela_melhores.horizontalHeader().setSortIndicatorShown(False)
        self.tabela_melhores.horizontalHeader().setStretchLastSection(True)
        self.tabela_melhores.verticalHeader().setVisible(True)
        self.tabela_melhores.verticalHeader().setCascadingSectionResizes(False)
        self.tabela_melhores.verticalHeader().setDefaultSectionSize(40)
        self.tabela_melhores.verticalHeader().setHighlightSections(True)
        self.tabela_melhores.verticalHeader().setMinimumSectionSize(40)
        self.tabela_melhores.verticalHeader().setSortIndicatorShown(False)
        self.tabela_melhores.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.splitter_9, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.data_grid, 2, 0, 1, 1)
        self.splitter_4 = QtGui.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setHandleWidth(20)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.linha = QtGui.QLabel(self.splitter_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.linha.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.linha.setFont(font)
        self.linha.setObjectName(_fromUtf8("linha"))
        self.data_hora = QtGui.QLabel(self.splitter_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(24, 40, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 146, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.data_hora.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.data_hora.setFont(font)
        self.data_hora.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.data_hora.setObjectName(_fromUtf8("data_hora"))
        self.gridLayout.addWidget(self.splitter_4, 3, 0, 1, 1)
        self.splitter_4.raise_()
        self.tempo.raise_()
        self.data_grid.raise_()
        self.title_grid.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 19))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFicheiro = QtGui.QMenu(self.menubar)
        self.menuFicheiro.setObjectName(_fromUtf8("menuFicheiro"))
        self.menuMudar_idioma = QtGui.QMenu(self.menuFicheiro)
        self.menuMudar_idioma.setObjectName(_fromUtf8("menuMudar_idioma"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setPriority(QtGui.QAction.HighPriority)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.Line1 = QtGui.QAction(MainWindow)
        self.Line1.setObjectName(_fromUtf8("Line1"))
        self.Line4 = QtGui.QAction(MainWindow)
        self.Line4.setObjectName(_fromUtf8("Line4"))
        self.Line6 = QtGui.QAction(MainWindow)
        self.Line6.setObjectName(_fromUtf8("Line6"))
        self.Line7 = QtGui.QAction(MainWindow)
        self.Line7.setObjectName(_fromUtf8("Line7"))
        self.Line8 = QtGui.QAction(MainWindow)
        self.Line8.setObjectName(_fromUtf8("Line8"))
        self.Line5 = QtGui.QAction(MainWindow)
        self.Line5.setObjectName(_fromUtf8("Line5"))
        self.actionSetLinha = QtGui.QAction(MainWindow)
        self.actionSetLinha.setObjectName(_fromUtf8("actionSetLinha"))
        self.actionExportar_Dados = QtGui.QAction(MainWindow)
        self.actionExportar_Dados.setObjectName(_fromUtf8("actionExportar_Dados"))
        self.actionPortugues = QtGui.QAction(MainWindow)
        self.actionPortugues.setObjectName(_fromUtf8("actionPortugues"))
        self.actionPolaco = QtGui.QAction(MainWindow)
        self.actionPolaco.setObjectName(_fromUtf8("actionPolaco"))
        self.menuMudar_idioma.addAction(self.actionPortugues)
        self.menuMudar_idioma.addAction(self.actionPolaco)
        self.menuFicheiro.addAction(self.actionExportar_Dados)
        self.menuFicheiro.addAction(self.menuMudar_idioma.menuAction())
        self.menuFicheiro.addAction(self.actionSair)
        self.menubar.addAction(self.menuFicheiro.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionSair, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FAURECIA - CRONÓMETRO DE MUDANÇA DE MOLDES", None))
        self.label_logged_in.setText(_translate("MainWindow", "ON-LINE:", None))
        self.label_titulo.setText(_translate("MainWindow", "CRONÓMETRO DE MUDANÇA DE MOLDES", None))
        self.tempo.setText(_translate("MainWindow", "00:00:000", None))
        self.label_ultimos.setText(_translate("MainWindow", "Últimos Tempos", None))
        self.data_hora_ultimos.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#18286e;\">Data/Hora</span></p></body></html>", None))
        self.label_user_latest.setText(_translate("MainWindow", "User", None))
        item = self.tabela_ultimos.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tabela_ultimos.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tabela_ultimos.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tabela_ultimos.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tabela_ultimos.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tabela_ultimos.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tabela_ultimos.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tabela_ultimos.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tabela_ultimos.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tabela_ultimos.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        __sortingEnabled = self.tabela_ultimos.isSortingEnabled()
        self.tabela_ultimos.setSortingEnabled(False)
        self.tabela_ultimos.setSortingEnabled(__sortingEnabled)
        self.label_objectivo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#18286e;\">Tempo objectivo</span></p></body></html>", None))
        self.tempo_objectivo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">01:30:000</span></p></body></html>", None))
        self.label_melhores.setText(_translate("MainWindow", "Melhores Tempos", None))
        self.data_hora_melhores.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#18286e;\">Data/Hora</span></p></body></html>", None))
        self.label_user_best.setText(_translate("MainWindow", "User", None))
        item = self.tabela_melhores.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tabela_melhores.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tabela_melhores.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tabela_melhores.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tabela_melhores.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tabela_melhores.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tabela_melhores.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tabela_melhores.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.tabela_melhores.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.tabela_melhores.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        __sortingEnabled = self.tabela_melhores.isSortingEnabled()
        self.tabela_melhores.setSortingEnabled(False)
        self.tabela_melhores.setSortingEnabled(__sortingEnabled)
        self.linha.setText(_translate("MainWindow", "FAA MOLDADOS - LINHA 1   ", None))
        self.data_hora.setText(_translate("MainWindow", "00-00-0000  00:00:00", None))
        self.menuFicheiro.setTitle(_translate("MainWindow", "Ficheiro", None))
        self.menuMudar_idioma.setTitle(_translate("MainWindow", "Mudar Idioma", None))
        self.actionSair.setText(_translate("MainWindow", "Sair", None))
        self.Line1.setText(_translate("MainWindow", "Linha 1", None))
        self.Line4.setText(_translate("MainWindow", "Linha 4", None))
        self.Line6.setText(_translate("MainWindow", "Linha 6", None))
        self.Line7.setText(_translate("MainWindow", "Linha 7", None))
        self.Line8.setText(_translate("MainWindow", "Linha 8", None))
        self.Line5.setText(_translate("MainWindow", "Linha 5", None))
        self.actionSetLinha.setText(_translate("MainWindow", "SetLinha", None))
        self.actionSetLinha.setToolTip(_translate("MainWindow", "SetLinha", None))
        self.actionExportar_Dados.setText(_translate("MainWindow", "Exportar Dados", None))
        self.actionPortugues.setText(_translate("MainWindow", "Portugues", None))
        self.actionPolaco.setText(_translate("MainWindow", "Polaco", None))

